<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/01_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [ ]:
import numpy as np

numbers=np.array([10,20,30])

print(numbers)

print(type(numbers))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers*2)

[ 20  40  60  80 100]
