<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/04 NumPy Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 04 Numpy Reshape

Reshaping, flattening, and expanding array dimensions.


## Array Reshaping & Flattening
Reshaping means changing the shape of an array without changing its data.

In [1]:
import numpy as np

arr = np.arange(12)
print("Original 1D:", arr)

# Reshape to 3x4 matrix
matrix_3x4 = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", matrix_3x4)

# Reshape using -1 for dynamic dimension calculation
matrix_2x6 = arr.reshape(2, -1)
print("Reshaped with -1 (2x6):\n", matrix_2x6)

Original 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped with -1 (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### Flattening Arrays: `.flatten()` vs `.ravel()`

In [1]:
flat = matrix_3x4.flatten()
rav = matrix_3x4.ravel()

print("Flattened:", flat)
print("Ravel:", rav)

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
