<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/07 NumPy Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 07 Numpy Broadcasting

Understanding array broadcasting rules and practical applications.


## NumPy Broadcasting Rules
Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

### Rules:
1. If dimensions differ, pad the smaller shape on the left with ones.
2. Arrays are compatible if dimensions match or if one of them is 1.

In [1]:
import numpy as np

matrix = np.ones((3, 3))
scalar = 5
print("Matrix + Scalar:\n", matrix + scalar)

matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_1d = np.array([10, 20, 30])

print("Matrix + Vector (Broadcasted along rows):\n", matrix_2d + vector_1d)

Matrix + Scalar:
 [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
Matrix + Vector (Broadcasted along rows):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Practical ML Example: Mean Centering Data

In [1]:
data = np.array([[10, 20], [30, 40], [50, 60]])
mean = np.mean(data, axis=0)
centered = data - mean
print("Original Data:\n", data)
print("Centered Data:\n", centered)

Original Data:
 [[10 20]
 [30 40]
 [50 60]]
Centered Data:
 [[-20. -20.]
 [  0.   0.]
 [ 20.  20.]]
