<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/08 NumPy Useful Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 08 Numpy Useful Functions

Essential creation and utility functions like zeros, ones, arange, and linspace.


## Array Creation Utilities
NumPy provides convenient functions to quickly initialize arrays filled with specific values or sequences.

In [1]:
import numpy as np

print("Zeros (2x3):\n", np.zeros((2, 3)))
print("Ones (3x2):\n", np.ones((3, 2)))
print("Full (2x2 filled with 7):\n", np.full((2, 2), 7))
print("Identity Matrix (3x3):\n", np.eye(3))

Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full (2x2 filled with 7):
 [[7 7]
 [7 7]]
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Sequence Generators: `np.arange()` vs `np.linspace()`

In [1]:
seq_arange = np.arange(0, 10, 2)
seq_linspace = np.linspace(0, 1, 5)

print("arange(0, 10, 2):", seq_arange)
print("linspace(0, 1, 5):", seq_linspace)

arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
