<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/11 NumPy Random Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11 Numpy Random Numbers

Random sampling, probability distributions, shuffling, and setting seeds.


## Random Number Generation
NumPy includes `np.random` for generating random arrays from various statistical distributions.

In [1]:
import numpy as np

np.random.seed(42)

rand_uniform = np.random.rand(3, 3)
rand_normal = np.random.randn(3, 3)
rand_ints = np.random.randint(10, 50, size=(2, 4))

print("Uniform Random:\n", rand_uniform)
print("Standard Normal:\n", rand_normal)
print("Random Integers:\n", rand_ints)

Uniform Random:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Standard Normal:
 [[-0.25243604  0.98132079 -0.56128688]
 [-0.28704256 -0.32049187 -0.35417439]
 [ 1.43940173  0.89311855 -0.67258416]]
Random Integers:
 [[30 48 24 35]
 [30 33 41 33]]


### Random Choice & Shuffling

In [1]:
items = np.array(['Red', 'Green', 'Blue', 'Yellow'])
chosen = np.random.choice(items, size=5, replace=True)
print("Random Choice:", chosen)

arr_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr_to_shuffle)
print("Shuffled Array:", arr_to_shuffle)

Random Choice: ['Blue' 'Green' 'Red' 'Green' 'Green']
Shuffled Array: [3 1 2 5 4]
