<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/14 NumPy Joining Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 14 Numpy Joining Arrays

Combining arrays using concatenate, stack, vstack, hstack, and dstack.


## Joining & Stacking Arrays
Combining multiple arrays along existing or new axes.

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

concat_axis0 = np.concatenate((a, b), axis=0)
concat_axis1 = np.concatenate((a, b), axis=1)

print("Concatenate Axis 0:\n", concat_axis0)
print("Concatenate Axis 1:\n", concat_axis1)

Concatenate Axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate Axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


### Convenience Stacking Functions: `vstack` & `hstack`

In [1]:
v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print("vstack (Vertical):\n", v_stacked)
print("hstack (Horizontal):\n", h_stacked)

vstack (Vertical):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack (Horizontal):
 [[1 2 5 6]
 [3 4 7 8]]
