<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/15 NumPy Splitting Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 15 Numpy Splitting Arrays

Dividing arrays into multiple sub-arrays with split, array_split, vsplit, hsplit.


## Splitting Arrays
Splitting is the reverse of joining, breaking a single array into multiple smaller arrays.

In [1]:
import numpy as np

arr = np.arange(1, 10)
splits = np.split(arr, 3)
print("Splitting 1D array into 3 parts:")
for idx, sub in enumerate(splits):
    print(f" Part {idx+1}:", sub)

Splitting 1D array into 3 parts:
 Part 1: [1 2 3]
 Part 2: [4 5 6]
 Part 3: [7 8 9]


### 2D Splitting: `vsplit` & `hsplit`

In [1]:
matrix = np.arange(16).reshape(4, 4)

upper, lower = np.vsplit(matrix, 2)
print("Upper 2 rows:\n", upper)
print("Lower 2 rows:\n", lower)

Upper 2 rows:
 [[0 1 2 3]
 [4 5 6 7]]
Lower 2 rows:
 [[ 8  9 10 11]
 [12 13 14 15]]
