<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/19 NumPy Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 19 Numpy Practice

Comprehensive practice exercises and challenges covering NumPy concepts.


## NumPy Comprehensive Practice
Challenge your understanding with these hands-on NumPy exercises.

### Exercise 1: Standardize a 2D Dataset
Given a 2D matrix of shape `(5, 3)`, calculate column means and standard deviations, then z-score normalize the matrix ($Z = \frac{X - \mu}{\sigma}$).

In [1]:
import numpy as np

np.random.seed(42)
X = np.random.randint(10, 100, size=(5, 3))
print("Original X:\n", X)

mu = np.mean(X, axis=0)
sigma = np.std(X, axis=0)

Z = (X - mu) / sigma
print("Z-score Normalized X:\n", Z)

Original X:
 [[61 24 81]
 [70 30 102]
 [84 96 30]
 [97 33 12]
 [31 62 1]]
Z-score Normalized X:
 [[-0.31682855 -0.91684784  0.86603417]
 [ 0.05431346 -0.70997193  1.37890479]
 [ 0.6322243  1.56566308 -0.37951016]
 [ 1.16885573 -0.60653398 -0.81914212]
 [-1.55856494  0.66768067 -1.04628669]]


### Exercise 2: Find Chessboard Pattern
Create an $8 \times 8$ 2D array with a checkerboard pattern of 0s and 1s.

In [1]:
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print("Chessboard Pattern:\n", chessboard)

Chessboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
