<a href="https://colab.research.google.com/github/VIJAYAPANDIANT/AI-ML-Learning/blob/main/Numpy/20 NumPy Mini Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20 Numpy Mini Project

Mini Project: Exploratory Data Analysis & Feature Engineering on Synthetic Housing Dataset.


## NumPy Mini-Project: Real Estate Dataset Analysis
In this mini-project, we analyze housing data containing `[Square Footage, Bedrooms, Bathrooms, Price]` using pure NumPy!

### Tasks:
1. Load/create synthetic real estate matrix.
2. Compute summary statistics (Mean, Median, Standard Deviation).
3. Filter outlier luxury homes ($Price > \$500,000$).
4. Compute Price per Square Foot.
5. Feature scale (Min-Max normalization) price column.

In [1]:
import numpy as np

np.random.seed(101)

sqft = np.random.randint(800, 3500, size=(10, 1))
beds = np.random.randint(1, 5, size=(10, 1))
baths = np.random.randint(1, 4, size=(10, 1))
price = sqft * 180 + beds * 15000 + np.random.randint(10000, 50000, size=(10, 1))

housing_dataset = np.hstack((sqft, beds, baths, price))
print("Dataset Matrix (First 5 homes):\n[SqFt, Beds, Baths, Price]")
print(housing_dataset[:5])

Dataset Matrix (First 5 homes):
[SqFt, Beds, Baths, Price]
[[  2074      4      2 466820]
 [  1946      4      2 443780]
 [  2276      4      3 514180]
 [  3277      4      2 682860]
 [  1599      1      3 325820]]


### Analysis & Feature Engineering

In [1]:
prices = housing_dataset[:, 3]
print(f"Average House Price: ${np.mean(prices):,.2f}")
print(f"Median House Price: ${np.median(prices):,.2f}")
print(f"Std Dev of Price: ${np.std(prices):,.2f}")

luxury_homes = housing_dataset[prices > 500000]
print(f"\nNumber of Luxury Homes (> $500k): {len(luxury_homes)}")

price_per_sqft = prices / housing_dataset[:, 0]
print("\nPrice per SqFt (First 5):", np.round(price_per_sqft[:5], 2))

normalized_price = (prices - np.min(prices)) / (np.max(prices) - np.min(prices))
print("\nNormalized Prices (First 5):", np.round(normalized_price[:5], 3))

Average House Price: $447,560.00
Median House Price: $455,300.00
Std Dev of Price: $132,604.14

Number of Luxury Homes (> $500k): 3

Price per SqFt (First 5): [225.08 228.05 225.91 208.37 203.76]

Normalized Prices (First 5): [0.638 0.58  0.757 1.    0.284]
